services:
  nostr-relay:
    image: ghcr.io/tkhumush/nostrarabiarelay:latest
    container_name: nostr-arabia-relay
    expose:
      - "7777"
    volumes:
      # Mount configuration files (for easy updates without rebuild)
      - ./strfry.conf:/app/strfry.conf:ro
      - ./noteguard.toml:/app/noteguard.toml:ro
      # Persist database
      - strfry-data:/app/strfry-db
    restart: unless-stopped
    networks:
      - nostr-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7777"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  blossom-server:
    image: ghcr.io/hzrd149/blossom-server:master
    container_name: blossom-server
    expose:
      - "3000"
    volumes:
      # Mount configuration file
      - ./blossom.yml:/app/config.yml:ro
      # Persist blob storage and database
      - blossom-data:/app/data
    environment:
      # Set admin password via environment variable
      # You can set this in your deployment secrets
      - BLOSSOM_ADMIN_PASSWORD=${BLOSSOM_ADMIN_PASSWORD:-changeme}
    restart: unless-stopped
    networks:
      - nostr-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  caddy:
    image: caddy:2-alpine
    container_name: caddy-proxy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"  # HTTP/3 support
    volumes:
      # Caddy configuration
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./nginx/html:/usr/share/caddy:ro  # Static files (reuse nginx/html directory)
      # Caddy data (certificates, etc.)
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - nostr-relay
      - blossom-server
    restart: unless-stopped
    networks:
      - nostr-network
    environment:
      - CADDY_ADMIN=0.0.0.0:2019  # Admin API endpoint

volumes:
  strfry-data:
    driver: local
  blossom-data:
    driver: local
  caddy-data:
    driver: local
  caddy-config:
    driver: local

networks:
  nostr-network:
    driver: bridge
