name: Build and Deploy Nostr Relay

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          command_timeout: 20m
          script: |
            # Create and navigate to deploy directory
            mkdir -p /home/nostrarabia/nostr-relay
            cd /home/nostrarabia/nostr-relay

            # Clone or update repo
            if [ ! -d .git ]; then
              # Remove any existing files if directory exists but no git repo
              rm -rf * .[!.]* 2>/dev/null || true
              git clone https://github.com/tkhumush/nostrarabiarelay.git .
            else
              git fetch origin
              git reset --hard origin/main
              git pull origin main
            fi

            # Login to GitHub Container Registry
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # Set environment variables for docker compose
            export BLOSSOM_ADMIN_PASSWORD="${{ secrets.BLOSSOM_ADMIN_PASSWORD }}"

            # Pull latest images using modern docker compose
            docker compose pull

            # Check if SSL certificates exist
            if ! docker compose run --rm certbot certificates 2>&1 | grep -q "Certificate Name: nostrarabia.com"; then
              echo "Certificates not found. Generating SSL certificates..."

              # Generate certificates using certbot standalone mode (before nginx starts)
              docker compose run --rm certbot certonly \
                --standalone \
                --email admin@nostrarabia.com \
                --agree-tos \
                --no-eff-email \
                -d nostrarabia.com \
                -d relay.nostrarabia.com \
                -d media.nostrarabia.com

              echo "SSL certificates generated successfully"
            else
              echo "SSL certificates already exist, skipping generation"
            fi

            # Deploy all services using modern docker compose
            docker compose up -d

            # Wait for services to be healthy
            sleep 10

            # Verify nginx configuration
            docker compose exec nginx nginx -t

            # Reload nginx to ensure it picks up any config changes
            docker compose exec nginx nginx -s reload

            # Show logs
            docker compose logs --tail=50
